### ISSUE TITLE
Wema bank

### ISSUE THREAD

**Issue by ascii-dev** [Adetona/keepthechange#12]
On the bank you use page, form only has wema bank, no other banks listed.

**Comment by Adetona** [comment]
Since wema  is the bank involved that's why we  do that. It's intentional , sammy. Thanks

**Comment by ascii-dev** [comment]
Oh... Cool... it shows multiple times though...

**Comment by Adetona** [comment]
That's also intentional. Or should we remove it ?

**Comment by ascii-dev** [comment]
I think it's confusing to the user, expecting to see multiple banks on the drop down but only gets to see wema  bank multiple times, I first thought it was a code error, showing wema only once would be cool enough. And you could put a disclaimer that it's cos wema is involved.

**Comment by Adetona** [comment]
Sammy.  If you can , please help replace it with other top 5 banks in Nigeria. Thanks for bringing this up.

**Comment by ascii-dev** [comment]
I will do that too and make a pull request of that before the end of the day...

**Comment by Adetona** [comment]
Yeah , thanks so much.

**Comment by ascii-dev** [comment]
Submitted a pull request...

**Comment by Adetona** [comment]
Accepted. Thanks.
